set_a = { 1, 2, 3, 'A', 'B', 'C' }
set_b = { 2, 3, 'B', 'D' }
print("Set A:")
print(set_a)
print("Set B:")
print(set_b)
print()
print("Schnittmenge über &")
print( set_a & set_b )
print()
print("Vereinigungsmenge über |")
print( set_a | set_b )
print()
print("Differenzmenge über - ")
print( set_a - set_b )
print()
print("Symmmetrische Differnz (entweder-oder) über ^")
print( set_a ^ set_b )
print()
print("Obermenge von > ")
print( set_a > set_b )